Actually submit the job and run the tests (facepalm)
Signed-off-by: Artie Poole <stuart.poole@canonical.com>

diff --git a/.github/workflows/integration_tests.yaml.yml b/.github/workflows/integration_tests.yaml.yml
--- a/.github/workflows/integration_tests.yaml.yml
+++ b/.github/workflows/integration_tests.yaml.yml
@@ -142,3 +142,43 @@ jobs:
           echo "::endgroup::"
 
           echo "test_path=job.yaml" >> $GITHUB_OUTPUT
+      - name: Submit TF job
+        id: submit
+        uses: canonical/testflinger/.github/actions/submit@main
+        continue-on-error: true
+        with:
+          poll: true
+          job-path: ${{ steps.prepare-tf-job.outputs.test_path }}
+      - name: Fetch and Display Artifacts
+        shell: bash
+        run: |
+          echo "::group::retrieve llvm-cov artifacts"
+            testflinger artifacts ${{steps.submit.outputs.id }}
+            tar -xvzf artifacts.tgz
+          echo "::endgroup::"
+
+          for f in artifacts/* ; do
+            echo "::group::$f"
+            cat "$f"
+            echo "::endgroup::"
+          done
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v5
+        with:
+          name: snap-testing-artifacts
+          path: artifacts/*
+      - name: Report test status
+        shell: bash
+        run: |-
+          if [ "${{ steps.submit.outcome }}" != "success" ]; then
+            echo "::error::test job didn't complete successfully"
+            exit 1
+          fi
+          if [[ ! -f artifacts/snap_test.log ]]; then
+            echo "::error::snap_test.log not found, did the tests fail to start?"
+            exit 1
+          fi
+          if grep -q "test result: FAIL" artifacts/snap_test.log; then
+            echo "::error::found failure phrase in snap_test.log"
+            exit 1
+          fi
